### ISSUE TITLE
Add a command line tool that reads JSON from files or stdin

### ISSUE THREAD

**Issue by olegp** [Nijikokun/generate-schema#1]
Would be great to have that included!

If you don't have time to do it, I may be able to and could send a pull request.

**Comment by Nijikokun** [comment]
Great idea :+1:

**Comment by Nijikokun** [comment]
I've released version `1.1.0` that has this feature :+1:

**Comment by olegp** [comment]
Awesome!

**Comment by Nijikokun** [comment]
https://www.youtube.com/watch?v=StTqXEQ2l-Y

**Comment by ahmadnassri** [comment]
:+1:
