### ISSUE TITLE
generate schema just displays data

### ISSUE THREAD

**Issue by mteegs** [nijikokun/generate-schema#11]
Hi. Not sure if I'm running this correctly but I input a JSON data file and run generate-schema -g <file.json> but all it does is display the data file back to me. Am I missing something here?

Thanks
Michael

**Comment by ShipraShalini** [comment]
I'm facing the same issue.
The command I'm running is:
generate-schema -m file.json

**Comment by DevByStarlight** [comment]
Hiya :)
I installed view homebrew - "Welcome to Generate Schema 2.1.1"
- If i use interactive mode it works fine.
- Also piping the json works okay - "cat test.json | generate-schema"
Downside is output has some interactive parts too (the ## is mine)
    ## Welcome to Generate Schema 2.1.1
    ##   Mode: json
    ## * Example Usage: 
    ##   > {a:'b'}
    ##   { a: { type: 'string' } }
    ## To quit type: exit
    ## > {

However, specifying files on command line fails and only regurgitates the original JSON file input.

Thus, I suspect the pull request for the read file issue (commit @e5292a9) may not have been included in the homebrew installed distribution version.

In the meantime, the pipe workaround is okay. Or I can build from source later too if the REPL message stuff becomes irksome. :)

Handy tool!
Thanks :)

**Comment by nijikokun** [comment]
Piping appears to be the best mode of generating data, if someone feels comfortable compiling a list of issues that I could tackle if you are still encountering them that would be appreciated, closing since this seems to be answered?
