### ISSUE TITLE
What is current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [nijikokun/generate-schema#13]
I'm not sure what's considered the current stable version for this software. Is it the 2.2.1 tag here on GitHub or the 2.1.1 on registry.npmjs.org or something else?

**Comment by ilovezfs** [comment]
bump on this. Not sure whether to update the Homebrew formula or not.

**Comment by nijikokun** [comment]
`2.3.0` is the most stable version as of today!

**Comment by nijikokun** [comment]
`2.3.1` is now the stable version, it fixes an issue with `json-schema draft 04`

**Comment by ilovezfs** [comment]
@nijikokun Thanks a lot! Voilà: https://github.com/Homebrew/homebrew-core/pull/5300/
