### ISSUE TITLE
usage of "JSON Schema" is confusing

### ISSUE THREAD

**Issue by zaggino** [Nijikokun/generate-schema#2]
`JSON Schema` is a set standard:
http://json-schema.org/
http://en.wikipedia.org/wiki/JSON#JSON_Schema

yet the output produced by this library is not a valid `JSON Schema`, so this should be clearly stated somewhere that this is not a generator for `JSON Schema`

**Comment by olegp** [comment]
Or better yet, actually have the output be valid JSON schema.

**Comment by Nijikokun** [comment]
> Or better yet, actually have the output be valid JSON schema.

I agree with this statement, wouldn't take too much, just change the output to be properties rather than directly nested, I have a feeling some would prefer to have both methods, output of the current style (for generic schema, then purely JSON Schema style)

**Comment by Nijikokun** [comment]
@zaggino can I get your input on #3? I've put examples of output, both a simple and advanced
