### ISSUE TITLE
motd should not be displayed when input is piped from another command

### ISSUE THREAD

**Issue by nagarajasr** [nijikokun/generate-schema#23]
i am trying to pipe a JSON string through generate-schema cli, like this:
```echo '{a: "b"}' | generate-schema```
the output includes the 'motd' welcome and usage message which makes it inconvenient to pipe the output to another command. i would like to do this:
```echo '{a: "b"}' | generate-schema | do_something_useful_with_schema```

could you please add a cli option (say, '-q' for quiet) so that generate-schema can be used seamlessly in a pipeline?

thanks

**Comment by nijikokun** [comment]
Released under [v2.4.0](https://github.com/nijikokun/generate-schema/releases/tag/v2.4.0)
