### ISSUE TITLE
Null keys break schema generation

### ISSUE THREAD

**Issue by ldodds** [nijikokun/generate-schema#27]
Given the test JSON:

```
{
 "items": [
   { "name": "foo", "details": { "a": "b" } },
   { "name": "bar", "details": null }
 ]
 
}
```

running the command line tool produces:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "details": {
            "type": "null"
          }
        },
        "required": [
          "name",
          "details"
        ]
      }
    }
  }
}
```

The `details` key has a type of null and no items. The null value for the second object in the `items` array in the example is overwriting the schema generated from the first.

So there is an ordering dependency which means that null values can result in lost schema information.

For a quick local fix I've put a conditional around [these lines](https://github.com/nijikokun/generate-schema/blob/master/src/schemas/json.js#L162-L163). If the type of the item is null and there's already a key for that property, then don't overwrite it. 

```
    if (type === 'null' && output.properties[key]) {
      //console.log(output.properties[key]);
    } else {
        output.properties[key] = {}
        output.properties[key].type = type
    }
```

I'm not sure that's a complete fix though, or even recommended. Just gives me a quick workaround!

**Comment by nijikokun** [comment]
Interesting...

**Comment by nijikokun** [comment]
So following the specification, when a field has multiple types it should become an array of primitives.

I have introduced this behavior in the following form:


```js
    if (output.properties[key]) {
      var entry = output.properties[key]
      var hasTypeArray = Array.isArray(entry.type)

      if (hasTypeArray && entry.type.indexOf(type) < 0) {
        entry.type.push(type)
      }

      if (!hasTypeArray && entry.type !== type) {
        entry.type = [entry.type, type]
      }

      continue
    }
 ```
 
 This should satisfy the expectations of your schema and validation
