### ISSUE TITLE
generateSchema.json does not create 'required' field on objects or array of 1

### ISSUE THREAD

**Issue by lpgeiger** [nijikokun/generate-schema#28]
I'm not sure if there is an option switch on this. I can't duplicate the example in the readme that shows the 'required' property on the schema.
I guess it requires multiple items in an array to find what is required. But shouldn't the smart default be that for objects or arrays of 1, that the keys all be required?

currently this:
```
 var schema = GenerateSchema.json('Product', { b:1 })

```
outputs:

```

schema {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Product Set",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "b": {
        "type": "number"
      }
    },
    "title": "Product"
  }
}

```

I'd expect to see `required: [ 'a' ]` 

Any thoughts on making that change?

**Comment by nijikokun** [comment]
It is planned but no movement yet

**Comment by nijikokun** [comment]
See #16
