### ISSUE TITLE
Creating objects from schema

### ISSUE THREAD

**Issue by amlwwalker** [nijikokun/generate-schema#30]
So I want to offer my users the ability to upload CSV and from that generate a mongoose schema, that i store in the DB against that user. When the user logs in, they can create a collection according to their personal schema. Using generate-schema I am able to create a `json` schema which looks like: 

    {
        "_id" : ObjectId("596a872cd1e59c6135fa7b2e"),
        "title" : "Product Set",
        "type" : "array",
        "items" : {
            "type" : "object",
            "properties" : {
                "booktitle" : {
                    "type" : "string"
                },
                "bookid" : {
                    "type" : "string"
                },
                "bookauthor" : {
                    "type" : "string"
                }
            },
            "required" : [ 
                "booktitle", 
                "bookid", 
                "bookauthor"
            ],
            "title" : "Product"
        },
        "＄schema" : "http://json-schema.org/draft-04/schema#"
    }

and store that in my `schema` collection. All good...

When I want to create a collection according to that schema, and store data in it using mongoose, I have tried to retrieve the schema from the database (which works) and then do

`var generatedSchema = GenerateSchema.mongoose(response)`

I then create a model from that with:

    var Model = db.models.Product || db.model('Product', generatedSchema); 

and create an item from that model

            var item = new Model({
                "_id": new ObjectID(),
              booktitle: 'The Godfather',
              bookid: 'abc123',
              bookauthor: 'Mario Puzo' 
            });

and save it:

    item.save(function(err, response) { ... })

I don't get any errors but when I save it, in the collection I just see:

    {
        "_id" : ObjectId("5970b1a584d396d7a2241eba"),
        "items" : {
            "required" : []
        },
        "__v" : 0
    }

Can you point me in the right direction as to why this isn't working? My suspicion is I am using the wrong type of schema to create the model.

Thanks

**Comment by nijikokun** [comment]
Still need assistance? Just saw this issue apologies
