### ISSUE TITLE
Integrated in transform

### ISSUE THREAD

**Issue by ritz078** [nijikokun/generate-schema#33]
Hi,

Thank you for this awesome library. Just wanted to tell you that I have integrated this functionality in https://transform.now.sh

**Comment by nijikokun** [comment]
Thanks for the support, would be cool to see a credits link somewhere 👍 

Cool site! I think I might add a "using the project" list to the readme.

**Comment by ritz078** [comment]
<img width="692" alt="screen shot 2017-11-14 at 1 14 58 am" src="https://user-images.githubusercontent.com/5389035/32745639-49935eac-c8d9-11e7-9780-18d1ae5f69a4.png">

I have added a link to the actual module. I will add the names of the developers ASAP. :)

**Comment by nijikokun** [comment]
Woah, awesome :)!
