### ISSUE TITLE
running from cli, not outputting schema

### ISSUE THREAD

**Issue by yehosef** [Nijikokun/generate-schema#6]
I have a dir where I have my json files - I did the following steps:

npm install generate-schema
ln -s node_modules/generate-schema/bin/generate-schema
./generate-schema post.json

it outputs the json of the file but does not output a schema or any error message.  I would expect that 1) it wouldn't print out the original json file and 2) would output the schema to stout so I could capture it.  Or at least print an error message if there was error.

I'm using node 0.12

**Comment by Nijikokun** [comment]
Can you make a gist with `post.json` ?

**Comment by pascalwhoop** [comment]
I can confirm. Having the same problem. Also generate-schema -m works oddly. But I used it with -g and it saved me lots of time so thanks for that!

**Comment by apeschel** [comment]
Looks like it's a problem with the filehandling, not the content. Here's an example:

Fails:
```
generate-schema foo.json
```
Works:
```
cat foo.json | generate-schema
```

**Comment by apeschel** [comment]
Relevant PR https://github.com/Nijikokun/generate-schema/pull/9

**Comment by Nijikokun** [comment]
This looks to be closed with the pulling of #9 will make a release later.
