### ISSUE TITLE
how to set required key as optional for some key in main json

### ISSUE THREAD

**Issue by mohsenomidi** [nijikokun/generate-schema#63]
Dear contributors, 

once to generate schema some fields are optional it means if they exist the schema will validate the type & etc and if it is not exist it just ignore in validation phase, now i have a json to create the schema, Is there any way to made some JSON fields as optional, i mean it does not need to put in required field list ?

**Comment by nijikokun** [comment]
Not as of yet, definitely open to a PR perhaps as an option passed to the generator with a list of key paths to ignore?
